version: "3" 
services:
    master:
        image: eeacms/jenkins-master
        ports:
            - "80:8080"
        volumes:
            - jenkins_home:/var/jenkins_home

    worker:
        build: jenkins-slave/ 
        environment:
            JENKINS_MASTER: "http://master:8080"
            JENKINS_NAME: "worker"
            JENKINS_USER: "danib"
            JENKINS_PASS: "1234567890"
            JENKINS_RETRY: "10"
        volumes:
        - jenkins-worker:/var/jenkins_home/worker

volumes:
    jenkins_home:
    jenkins-worker:

