version: '3'
services:
  master:
    build: ./jenkins-master
    ports:
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net
  slave:
    build: ./jenkins-slave

volumes:
  jenkins-data:
  jenkins-log:
networks:
  jenkins-net:
